apiVersion: apps/v1
kind: Deployment
metadata:
  name: webpage
spec:
  selector:
    matchLabels:
      app: webpage
  template:
    metadata:
      labels:
        app: webpage
      annotations:
        service.beta.kubernetes.io/oci-load-balancer-shape: "flexible"
        service.beta.kubernetes.io/oci-load-balancer-shape-flex-min: "10"
        service.beta.kubernetes.io/oci-load-balancer-shape-flex-max: "10"
    spec:
      containers:
      - name: webpage
        image: fabricioveronez/pagina-exemplo:blue
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: webpage
  namespace: webcolor
  labels:
    app: webpage
spec:
  type: ClusterIP
  selector:
    app: webpage
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP



